"""
Django settings for ourbiz project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q(2tc^ov3%a++i8a2z01&+&(i7-yz3!)usfnbq8)u8wp8$(!2u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "13.43.246.242",
    "localhost",
    "127.0.0.1",
    "www.ourbiz.ao",
    "ourbiz.ao",
    "api.v1.ourbiz.ao",
]

# Configuração CORS (se estiver usando django-cors-headers)
CORS_ALLOWED_ORIGINS = [
    "https://13.43.246.242",
    "https://www.ourbiz.ao",
    "https://ourbiz.ao",
    "https://api.v1.ourbiz.ao",
    "https://127.0.0.1",
    "https://localhost",
    "http://localhost:5173"
]

# Domínios confiáveis para CSRF
CSRF_TRUSTED_ORIGINS = [
    "https://13.43.246.242",
    "https://www.ourbiz.ao",
    "https://ourbiz.ao",
    "https://api.v1.ourbiz.ao",
    "https://127.0.0.1",
    "https://localhost",
    "http://localhost:5173"

]

# Segurança
SECURE_SSL_REDIRECT = False  # True se usar HTTPS obrigatório
CSRF_COOKIE_SECURE = False   # True se só aceitar cookie via HTTPS
SESSION_COOKIE_SECURE = False
USE_X_FORWARDED_HOST = True  # Necessário se estiver atrás de proxy/load balancer

# CSRF via sessão
CSRF_USE_SESSIONS = True  # Alternativa para evitar falhas no CSRF
CSRF_COOKIE_HTTPONLY = True  # Impede que JavaScript acesse o cookie CSRF
CSRF_COOKIE_SAMESITE = 'Lax'  # Permite CSRF apenas para o mesmo site

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')



# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'ninja',
    'ap_solicitar',
    'usuario',
    'funcionario',
    'servico',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]
# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_HOST = "mail.adacapital.ao"  # Servidor SMTP do seu e-mail empresarial
EMAIL_HOST = "smtp.gmail.com"  # Servidor SMTP do Gmail
EMAIL_PORT = 587  # Use 465 para SSL ou 587 para TLS
EMAIL_USE_TLS = True  # Se usar a porta 465, mude para EMAIL_USE_SSL = True
EMAIL_USE_SSL = False  # Se usar SSL (porta 465), defina como True
EMAIL_HOST_USER = "adelinoemilianoa@gmail.com"  # Seu e-mail empresarial
EMAIL_HOST_PASSWORD = "sbfl ucob pajy tklq"  # Substitua pela senha correta#X
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# Configuração do Redis como backend do Celery
CELERY_BROKER_URL = "sqla+sqlite:///celerydb.sqlite3"
CELERY_RESULT_BACKEND = "db+sqlite:///celery_results.sqlite3"

# Formato das tarefas
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"

# Tentar reconectar ao iniciar
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

"""# Configuração do Celery
EMAIL_HOST = "mail.ourbiz.ao"  # Servidor SMTP do seu e-mail empresarial
#EMAIL_HOST = "smtp.gmail.com"  # Servidor SMTP do Gmail
EMAIL_PORT = 587  # Use 465 para SSL ou 587 para TLS
EMAIL_USE_TLS = True  # Se usar a porta 465, mude para EMAIL_USE_SSL = True
EMAIL_USE_SSL = False  # Se usar SSL (porta 465), defina como True
EMAIL_HOST_USER = "comercial@ourbiz.ao"  # Seu e-mail empresarial
EMAIL_HOST_PASSWORD = "#Ou!928003757!Bi*"  # Substitua pela senha correta#X


CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_BROKER_CONNECTIONe_RETRY_ON_STARTUP = True

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # Servidor SMTP do Gmail
EMAIL_PORT = 587  # Porta SMTP padrão para TLS
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "adelinoemilianoa@gmail.com"  # Substitua pelo seu e-mail
EMAIL_HOST_PASSWORD = "sbfl ucob pajy tklq"  # Substitua pela senha ou use "App Password"
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
"""

# Configurações do JWT
SECRET_KEY = "sua_chave_screta"  # Substitua por uma chave forte
ALGORITHM = "HS256"
TOKEN_EXPIRATION_MINUTES = 60
