# Generated by Django 5.2.1 on 2025-08-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_requerente', models.CharField(max_length=255)),
                ('email_requerente', models.EmailField(max_length=254)),
                ('tem_dominio', models.BooleanField(default=False)),
                ('dominio', models.CharField(blank=True, max_length=255, null=True)),
                ('tem_logotipo', models.BooleanField(default=False)),
                ('sobre_empresa', models.TextField(blank=True, null=True)),
                ('integracoes', models.TextField(blank=True, null=True)),
                ('site_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('commentarios', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('objetivo_site', models.ManyToManyField(blank=True, to='ap_solicitar.objetivo')),
            ],
        ),
    ]
