# Generated by Django 5.2.1 on 2025-08-29 14:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionario', '0001_initial'),
        ('usuario', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('tipo', models.CharField(choices=[('consultoria_pequenas_empresas', 'Consultoria para Pequenas Empresas'), ('consultoria_startups', 'Consultoria para Startups'), ('outros', 'Outros')], max_length=50)),
                ('preco_base', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SolicitacaoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servico', models.CharField(choices=[('corrente', 'Corrente'), ('avulso', 'Avulso')], max_length=50)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=30)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(default=datetime.date.today)),
                ('duracao_meses', models.PositiveIntegerField(default=1)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('factura_servico', models.FileField(upload_to='temporarias/')),
                ('tem_factura', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionario.funcionario')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ap_solicitar.servico')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_requerente', models.CharField(max_length=255)),
                ('email_requerente', models.EmailField(max_length=254)),
                ('telefone_requerente', models.CharField(blank=True, max_length=15, null=True)),
                ('tem_dominio', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Ainda não sei o que é isso', 'Ainda não sei o que é isso')], max_length=50, null=True)),
                ('dominio', models.CharField(blank=True, max_length=255, null=True)),
                ('tem_logotipo', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em processo de criação', 'Em processo de criação')], max_length=50, null=True)),
                ('sobre_empresa', models.TextField(blank=True, null=True)),
                ('integracoes', models.TextField(blank=True, null=True)),
                ('site_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('metodo_contato', models.CharField(blank=True, max_length=100, null=True)),
                ('commentarios', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('objetivo_site', models.ManyToManyField(blank=True, to='ap_solicitar.objetivo')),
            ],
        ),
    ]
