# Generated by Django 5.2.1 on 2025-08-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_solicitar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiterequest',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
