# Generated by Django 5.2.1 on 2025-10-04 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_solicitar', '0001_initial'),
        ('servico', '0002_alter_plano_preco_mensal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='factura_servico',
            field=models.FileField(blank=True, null=True, upload_to='temporarias/'),
        ),
        migrations.AlterField(
            model_name='solicitacaoservico',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servico.plano'),
        ),
    ]
