# Generated by Django 5.2.1 on 2025-10-27 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ap_solicitar', '0002_alter_solicitacaoservico_factura_servico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacaoservico',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='solicitacaoservico',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='solicitacaoservico',
            name='tem_factura',
        ),
        migrations.RemoveField(
            model_name='solicitacaoservico',
            name='tipo_servico',
        ),
    ]
