# Generated by Django 5.2.1 on 2025-08-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap_solicitar', '0002_websiterequest_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='websiterequest',
            name='telefone',
        ),
        migrations.AddField(
            model_name='websiterequest',
            name='telefone_requerente',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='tem_dominio',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Ainda não sei o que é isso', 'Ainda não sei o que é isso')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='websiterequest',
            name='tem_logotipo',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Em processo de criação', 'Em processo de criação')], max_length=50, null=True),
        ),
    ]
