# Generated by Django 5.2.1 on 2025-08-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nif',
            new_name='numero_inss',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nome_empresa',
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero_nif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
