# Generated by Django 5.2.1 on 2025-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_remove_usuario_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('cliente', 'cliente'), ('funcionario', 'funcionario')], default='cliente', max_length=20),
        ),
    ]
