# Generated by Django 5.2.1 on 2025-09-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='preco_mensal',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
