# Generated by Django 5.2.1 on 2025-10-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_alter_plano_preco_mensal'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='tipo_servico',
            field=models.CharField(choices=[('corrente', 'Corrente'), ('avulso', 'Avulso')], default='corrente', max_length=50),
        ),
    ]
