# Generated by Django 5.2.1 on 2025-11-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CordenadasBancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_conta', models.CharField(max_length=50)),
                ('titular_conta', models.CharField(max_length=100)),
                ('iban', models.CharField(blank=True, max_length=34, null=True)),
                ('numero_express', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_bic', models.CharField(blank=True, max_length=11, null=True)),
            ],
        ),
    ]
